// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuEzBoZUAD2ucqZf-8EMlxa6M9zD-XSQE',
    appId: '1:225403963884:web:38315666f4b3c318bfd8c9',
    messagingSenderId: '225403963884',
    projectId: 'wheres-my-bus-17123',
    authDomain: 'wheres-my-bus-17123.firebaseapp.com',
    storageBucket: 'wheres-my-bus-17123.firebasestorage.app',
    measurementId: 'G-1145PH9E0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYCfowUHR6xk7IUfi1M2Xr0Wxza8KwR8Y',
    appId: '1:225403963884:android:28659fd904bdb8b9bfd8c9',
    messagingSenderId: '225403963884',
    projectId: 'wheres-my-bus-17123',
    storageBucket: 'wheres-my-bus-17123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKWjQksYapFyywP_GEn3ZxfeYZEOSVyRo',
    appId: '1:225403963884:ios:0780b3bc0bf0cd2fbfd8c9',
    messagingSenderId: '225403963884',
    projectId: 'wheres-my-bus-17123',
    storageBucket: 'wheres-my-bus-17123.firebasestorage.app',
    iosBundleId: 'com.example.wheresMyBus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKWjQksYapFyywP_GEn3ZxfeYZEOSVyRo',
    appId: '1:225403963884:ios:0780b3bc0bf0cd2fbfd8c9',
    messagingSenderId: '225403963884',
    projectId: 'wheres-my-bus-17123',
    storageBucket: 'wheres-my-bus-17123.firebasestorage.app',
    iosBundleId: 'com.example.wheresMyBus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuEzBoZUAD2ucqZf-8EMlxa6M9zD-XSQE',
    appId: '1:225403963884:web:516ebad76dd5253bbfd8c9',
    messagingSenderId: '225403963884',
    projectId: 'wheres-my-bus-17123',
    authDomain: 'wheres-my-bus-17123.firebaseapp.com',
    storageBucket: 'wheres-my-bus-17123.firebasestorage.app',
    measurementId: 'G-V8R04ZREK6',
  );

}